### ISSUE TITLE
Installation via requirements.txt file has mysql dependency 

### ISSUE THREAD

**Issue by davidfic** [SawdustSoftware/flask-chassis#1]
When installing I ran into the following error:

```
Building a Distribute egg in /home/user/.virtualenvs/chassis/build/MySQL-python

/home/user/.virtualenvs/chassis/build/MySQL-python/distribute-0.6.28-py2.7.egg

sh: 1: mysql_config: not found

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/user/.virtualenvs/chassis/build/MySQL-python/setup.py", line 18, in <module>

    metadata, options = get_config()

  File "setup_posix.py", line 43, in get_config

    libs = mysql_config("libs_r")

  File "setup_posix.py", line 25, in mysql_config

    raise EnvironmentError("%s not found" % (mysql_config.path,))

EnvironmentError: mysql_config not found
```

I had to install libmysqlclient-dev  to get around this.

**Comment by malicustommade** [comment]
Ooops, left over. 9ca8c4d8658ffa53d10fa3f2e7c9dbd1db1eafaa should fix it. Cheers, thanks :)

**Comment by namnd** [comment]
Hi guys, i ran into the same problem, can you post solution how to fix it here? Thanks a alot

**Comment by makmanalp** [comment]
Hey - I no longer work here so I don't really have write access to this repo, but I've been maintaining my fork here if you're still interested: https://github.com/makmanalp/flask-chassis

Re: the issue, it's surprising to me - the mysql dependency seems to be removed completely. Do you have a more detailed log?

**Comment by namnd** [comment]
Found the solution here http://learninglamp.wordpress.com/2010/02/21/mysqldb-python-mysql-and-os-x-a-match-made-in-satans-bum/ 
Apparently, the issue came from mixing 64 bit and 32 bit versions of python and MySQL.
